import { Link } from 'react-router-dom'

const faqs = [
  ['Wie beginnt eine Zahnbehandlung in Antalya?', 'Am Anfang steht eine unverbindliche Anfrage. Vorhandene Röntgenbilder und Angaben zu Ihren Wünschen können eine erste Orientierung ermöglichen. Eine endgültige Diagnose und ein verbindlicher Behandlungsplan entstehen jedoch erst nach der persönlichen Untersuchung durch den behandelnden Zahnarzt.'],
  ['Sind Flug, Hotel und Transfer im Behandlungspreis enthalten?', 'Das hängt vom individuellen Angebot ab. Medizinische Behandlung, Flug, Unterkunft und Transfer sollten transparent und getrennt ausgewiesen werden. Smilevia koordiniert organisatorische Leistungen nur in dem Umfang, der schriftlich bestätigt wurde.'],
  ['Wer ist für die medizinische Behandlung verantwortlich?', 'Die offengelegte Partnerklinik und der behandelnde Zahnarzt tragen die medizinische Verantwortung. Smilevia ist keine Zahnarztpraxis und übernimmt die Kommunikation sowie die organisatorische Koordination der Zahnreise.'],
  ['Wie wird die Nachsorge in der Schweiz geplant?', 'Vor der Reise sollte geklärt werden, welche Kontrollen erforderlich sind, welche Dokumente Sie erhalten und wer bei Beschwerden kontaktiert wird. Die konkrete Nachsorge richtet sich nach der Behandlung und den Empfehlungen des Zahnarztes.'],
]

export function SeoGuide() {
  const schema = { '@context':'https://schema.org', '@type':'FAQPage', mainEntity:faqs.map(([question,answer])=>({ '@type':'Question', name:question, acceptedAnswer:{ '@type':'Answer', text:answer } })) }
  return <section className="bg-[#ecf0fa] px-4 py-20 md:px-8 md:py-28" aria-labelledby="dental-guide-title"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><div className="mx-auto max-w-[1120px]"><p className="eyebrow">Ratgeber für Patienten aus der Schweiz</p><h2 id="dental-guide-title" className="section-title mt-5">Zahnbehandlung in Antalya:<br/><span className="hero-script font-normal italic text-[#4f6fd6]">sicher planen</span> und vergleichen.</h2><p className="mt-7 max-w-3xl text-lg leading-8 text-[#55607a]">Wer nach einer <strong>Zahnbehandlung in der Türkei</strong>, einem <strong>Zahnarzt in Antalya</strong> oder <strong>Zahnimplantaten in Antalya</strong> sucht, benötigt mehr als einen günstigen Preis. Entscheidend sind ein nachvollziehbarer Behandlungsplan, eine klare Rollenverteilung und eine realistische Organisation vor, während und nach der Reise. Smilevia begleitet Patientinnen und Patienten aus der Schweiz bei diesen organisatorischen Schritten. Die medizinische Beratung und Behandlung bleibt vollständig in der Verantwortung der offengelegten Partnerklinik.</p>

      <div className="mt-12 overflow-hidden rounded-[32px]"><img src="/smilevia-media/seo-guide-consultation.jpg" alt="Persönliche Beratung zur Planung einer Zahnbehandlung in Antalya" className="h-[260px] w-full object-cover md:h-[420px]"/></div>

      <div className="seo-copy mt-12 grid gap-5 lg:grid-cols-2">
        <article><h3>Zahnreise von der Schweiz nach Antalya vorbereiten</h3><p>Eine gut vorbereitete <strong>Zahnreise von der Schweiz in die Türkei</strong> beginnt mit vollständigen Informationen. Teilen Sie mit, welche Beschwerden bestehen, welche Behandlung Sie sich wünschen und ob aktuelle Röntgenbilder vorhanden sind. Diese Unterlagen können der Partnerklinik eine erste Einschätzung erleichtern. Sie ersetzen jedoch keine Untersuchung vor Ort. Erst nach der klinischen Untersuchung kann der behandelnde Zahnarzt feststellen, welche Therapie medizinisch geeignet ist.</p><p>Vor einer Buchung sollten Sie einen schriftlichen Plan erhalten. Darin sollten die vorgesehenen Behandlungsschritte, verwendeten Materialien, voraussichtlichen Termine, Aufenthaltsdauer und Kostenfaktoren verständlich aufgeführt sein. Fragen Sie auch nach möglichen Alternativen, Risiken und der Nachsorge. Eine seriöse Planung berücksichtigt, dass sich ein vorläufiger Plan nach der Untersuchung verändern kann.</p></article>
        <article><h3>Zahnimplantate in Antalya: Planung statt Preisvergleich</h3><p>Bei <strong>Zahnimplantaten in Antalya</strong> hängt der Ablauf vom individuellen Befund ab. Knochenangebot, Mundgesundheit, Anzahl der fehlenden Zähne und bestehende Erkrankungen können die Planung beeinflussen. Manche Implantatbehandlungen benötigen mehrere Phasen und mehr als eine Reise. Zwischen dem Einsetzen eines Implantats und der endgültigen Versorgung kann eine Heilungszeit notwendig sein.</p><p>Vergleichen Sie deshalb nicht nur pauschale Paketpreise. Ein aussagekräftiges Angebot benennt Implantatsystem, Anzahl der Implantate, möglichen Knochenaufbau, prothetische Versorgung und Laborleistungen. Wichtig ist ausserdem, dass Sie Implantatpass, Behandlungsbericht, Röntgenunterlagen und Materialinformationen erhalten. Diese Dokumente können für spätere Kontrollen in der Schweiz relevant sein.</p></article>
        <article><h3>Veneers und Zahnkronen in der Türkei</h3><p>Bei einer ästhetischen <strong>Zahnbehandlung in Antalya</strong> werden häufig Veneers, Zahnkronen oder eine Kombination verschiedener Massnahmen besprochen. Veneers sind dünne Verblendschalen für sichtbare Zahnflächen. Zahnkronen umfassen einen grösseren Teil des Zahns und können bei stärker geschädigter Zahnsubstanz angezeigt sein. Welche Lösung infrage kommt, lässt sich nicht allein anhand eines Fotos entscheiden.</p><p>Vor einem sogenannten Smile Makeover sollten Biss, Zahnfleisch, vorhandene Füllungen und gesunde Zahnsubstanz beurteilt werden. Fragen Sie, wie viel Zahnsubstanz bearbeitet werden muss und ob zahnschonendere Alternativen möglich sind. Das Ziel sollte nicht nur ein helles Erscheinungsbild sein, sondern eine funktionelle, individuell geplante und langfristig kontrollierbare Versorgung.</p></article>
        <article><h3>Kosten einer Zahnbehandlung in der Türkei verstehen</h3><p>Die <strong>Kosten einer Zahnbehandlung in der Türkei</strong> lassen sich ohne Befund nicht zuverlässig bestimmen. Anzahl und Art der Behandlungen, Materialwahl, Laboraufwand, notwendige Vorbehandlungen und Aufenthaltsdauer wirken sich auf das Angebot aus. Sehr niedrige Werbepreise beziehen sich möglicherweise nur auf einen Teil der Leistung. Lassen Sie sich deshalb schriftlich erklären, was enthalten ist und welche zusätzlichen Kosten entstehen können.</p><p>Flug, Hotel, Flughafentransfer und Fahrten zur Klinik sind organisatorische Leistungen und sollten von der medizinischen Behandlung unterscheidbar bleiben. Smilevia unterstützt bei der Abstimmung dieser Schritte, sofern sie im individuellen Angebot bestätigt sind. Die Zahlung, Stornierungsbedingungen, Garantiebedingungen und Zuständigkeiten müssen vor einer verbindlichen Buchung eindeutig geregelt werden.</p></article>
        <article><h3>Persönliche Betreuung aus der Schweiz</h3><p>Bei einer grenzüberschreitenden Behandlung ist verständliche Kommunikation besonders wichtig. Smilevia bietet einen festen Ansprechpartner für die organisatorische Begleitung. Dazu gehören die Vorbereitung der Anfrage, die Abstimmung mit der Partnerklinik sowie auf Wunsch die Koordination von Termin, Transfer und Unterkunft. Medizinische Fragen werden an die verantwortliche Klinik weitergeleitet und von medizinischem Fachpersonal beantwortet.</p><p>Die konkrete Klinik, der behandelnde Zahnarzt und der medizinische Leistungserbringer werden offengelegt, bevor Gesundheitsdaten übermittelt oder verbindliche Entscheidungen getroffen werden. So bleibt erkennbar, wer für Organisation, medizinische Aufklärung, Behandlung und Nachsorge verantwortlich ist.</p></article>
        <article><h3>Nachsorge nach der Zahnbehandlung</h3><p>Eine Zahnreise endet nicht mit dem Rückflug. Klären Sie vorab, wann Kontrollen stattfinden sollen, wie die Mundhygiene angepasst werden muss und an wen Sie sich bei Schmerzen, Schwellung oder einem technischen Problem wenden. Nach umfangreichen Behandlungen können weitere Termine notwendig sein. Bei akuten oder ungewöhnlichen Beschwerden sollte zeitnah zahnärztlicher Rat eingeholt werden.</p><p>Lassen Sie sich alle Behandlungsunterlagen aushändigen und bewahren Sie diese dauerhaft auf. Regelmässige Kontrollen und professionelle Zahnreinigungen bleiben auch nach einer Behandlung in Antalya wichtig. Smilevia kann die organisatorische Kommunikation unterstützen, ersetzt jedoch weder die Untersuchung noch eine medizinische Nachsorge durch qualifizierte Zahnärzte.</p></article>
      </div>

      <div className="mt-16"><p className="eyebrow">Häufige Fragen</p><h3 className="mt-4 text-3xl font-black">Was Patienten vor einer Zahnreise wissen möchten</h3><div className="mt-7 space-y-3">{faqs.map(([question,answer])=><details key={question} className="glass group rounded-[22px] p-5 md:p-6"><summary className="cursor-pointer list-none pr-8 font-black">{question}<span className="float-right text-[#4f6fd6] group-open:rotate-45">＋</span></summary><p className="mt-4 max-w-4xl leading-7 text-[#55607a]">{answer}</p></details>)}</div></div>
      <div className="mt-12 glass-dark rounded-[28px] bg-[#15265e]/55 p-7 text-white md:flex md:items-center md:justify-between md:p-10"><div><h3 className="text-2xl font-black">Ihre Situation unverbindlich besprechen</h3><p className="mt-2 max-w-2xl text-sm leading-6 text-white/60">Senden Sie zunächst nur die notwendigen Kontaktdaten. Gesundheitsunterlagen werden erst nach Abstimmung über einen geeigneten sicheren Weg angefordert.</p></div><Link to="/randevu-al" className="mt-6 inline-block shrink-0 rounded-full bg-[#4da8ff] px-6 py-4 font-bold text-[#0a1130] md:mt-0">Anfrage starten ↗</Link></div>
      <p className="mt-7 text-xs leading-6 text-[#6b7488]"><strong>Medizinischer Hinweis:</strong> Diese Informationen dienen der allgemeinen Orientierung und ersetzen keine zahnärztliche Untersuchung, Diagnose oder individuelle Behandlungsempfehlung.</p>
    </div></section>
}
