export const serviceData = [
  { slug:'estetik-dis-tedavileri', image:'/about/about-4-1.webp', category:'Zahnmedizin', title:'Ästhetische Zahnmedizin', summary:'Individuelle Lösungen für Form, Farbe und Harmonie Ihres Lächelns.', intro:'Ästhetische Zahnmedizin verbindet Zahngesundheit mit einem natürlichen Erscheinungsbild. Nach einer Untersuchung plant die Partnerklinik mögliche Behandlungen passend zu Gesicht, Zahnstruktur und persönlichen Wünschen.', points:['Smile Design und digitale Planung','Veneers und keramische Versorgungen','Form- und Farbkorrekturen','Individuell kombinierbare Behandlungen'] },
  { slug:'implant-tedavisi', image:'/about/about-1-1.webp', category:'Zahnbehandlung', title:'Zahnimplantate', summary:'Festsitzende Lösungen zum Ersatz fehlender Zähne.', intro:'Implantate können einzelne oder mehrere fehlende Zähne ersetzen. Ob eine Implantation geeignet ist, wird anhand der Mundsituation, des Knochenangebots und der allgemeinen Gesundheit beurteilt.', points:['Digitale Vorplanung','Einzelzahn- und Mehrfachversorgung','Festsitzender Zahnersatz','Individuelle Nachsorgeplanung'] },
  { slug:'dis-beyazlatma', image:'/smilevia-media/home-before.webp', category:'Zahnmedizin', title:'Zahnaufhellung', summary:'Professionelle Aufhellung für ein frischeres Erscheinungsbild.', intro:'Eine professionelle Zahnaufhellung kann Verfärbungen reduzieren. Vorab prüft die Partnerklinik Zähne und Zahnfleisch und klärt, welche Methode sinnvoll ist.', points:['Zahnärztliche Voruntersuchung','Professionelle Anwendung','Hinweise zur Pflege danach','Ergebnis abhängig von Ausgangsfarbe und Gewohnheiten'] },
  { slug:'dis-cekimi', image:'/smilevia-media/home-4.webp', category:'Zahnbehandlung', title:'Zahnentfernung', summary:'Schonende Entfernung nicht erhaltungsfähiger Zähne.', intro:'Eine Zahnentfernung wird erwogen, wenn ein Zahn nicht sinnvoll erhalten werden kann. Die Entscheidung trifft der behandelnde Zahnarzt nach klinischer und radiologischer Untersuchung.', points:['Untersuchung und Röntgenbeurteilung','Lokale Betäubung','Hinweise für die Heilungsphase','Planung eines möglichen Zahnersatzes'] },
  { slug:'ortodonti', image:'/about/about-6.webp', category:'Zahnbehandlung', title:'Kieferorthopädie', summary:'Behandlung von Zahnfehlstellungen für Funktion und Ästhetik.', intro:'Kieferorthopädische Behandlungen bewegen Zähne kontrolliert in eine günstigere Position. Methode und Dauer richten sich nach Fehlstellung und individuellem Befund.', points:['Klassische Zahnspangen','Transparente Aligner','Digitale Verlaufskontrolle','Individuelle Retentionsplanung'] },
  { slug:'agiz-ve-cene-cerrahisi', image:'/about/about-3-1.webp', category:'Zahnmedizin', title:'Oral- und Kieferchirurgie', summary:'Chirurgische Behandlung komplexer Befunde im Mund- und Kieferbereich.', intro:'Oralchirurgische Eingriffe können unter anderem bei Weisheitszähnen, Entzündungen oder komplexen Implantatfällen erforderlich sein. Art und Umfang müssen fachärztlich beurteilt werden.', points:['Operative Zahnentfernung','Behandlung von Entzündungen','Knochenaufbau nach Indikation','Individuelle Risikoaufklärung'] },
  { slug:'periodontoloji', image:'/smilevia-media/home-1.webp', category:'Zahnbehandlung', title:'Parodontologie', summary:'Diagnostik und Behandlung von Zahnfleisch- und Zahnbetterkrankungen.', intro:'Parodontologische Behandlung zielt darauf, Entzündungen des Zahnfleisches und des Zahnhalteapparats zu kontrollieren und Zähne langfristig zu stabilisieren.', points:['Zahnfleischdiagnostik','Professionelle Tiefenreinigung','Individuelle Mundhygieneberatung','Regelmässige Nachsorge'] },
  { slug:'sedasyon', image:'/about/about-5-1.webp', category:'Zahnbehandlung', title:'Sedierung', summary:'Unterstützung für entspanntere Behandlungen bei geeigneten Patienten.', intro:'Eine Sedierung kann bei ausgeprägter Behandlungsangst oder bestimmten Eingriffen erwogen werden. Ob sie medizinisch geeignet ist und welche Form infrage kommt, entscheidet das Behandlungsteam.', points:['Ärztliche Vorabklärung','Überwachung während der Behandlung','Individuelle Dosierung','Begleitperson und Nachsorge erforderlich'] },
  { slug:'pedodonti', image:'/about/about-2-1.webp', category:'Zahnmedizin', title:'Kinderzahnmedizin', summary:'Altersgerechte Vorsorge und Behandlung für Kinder.', intro:'Kinderzahnmedizin begleitet die Entwicklung von Milch- und bleibenden Zähnen. Ein behutsamer, altersgerechter Umgang steht dabei im Mittelpunkt.', points:['Vorsorge und Kontrollen','Kariesbehandlung','Fissurenversiegelung nach Indikation','Eltern- und Mundhygieneberatung'] },
]

export type ServiceItem = typeof serviceData[number]
