import { Link } from 'react-router-dom'
import { MotionBackground } from './MotionBackground'

export function TravelSupport() {
  const steps = [
    ['01','Flugplanung','Sie wählen und buchen Ihren Flug. Wir stimmen Ihre Ankunft mit dem Behandlungsplan ab.'],
    ['02','Flughafentransfer','Auf Wunsch koordinieren wir die Abholung am Flughafen und die Fahrten zur Partnerklinik.'],
    ['03','Unterkunft','Wir unterstützen bei der Auswahl einer passenden Unterkunft für die geplante Aufenthaltsdauer.'],
    ['04','Persönliche Begleitung','Während Ihres Aufenthalts bleiben wir Ihr direkter Ansprechpartner für organisatorische Fragen.'],
  ]
  return <section className="relative overflow-hidden bg-[#2c4956] px-4 py-20 text-white md:px-8 md:py-32"><MotionBackground/><div className="relative mx-auto max-w-[1320px]"><div className="grid gap-5 lg:grid-cols-[1.05fr_.95fr]"><div className="relative min-h-[520px] overflow-hidden rounded-[38px]"><img src="/smilevia-media/transfer.png" alt="Symbolische Darstellung des Flughafentransfers in Antalya" className="h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-[#0a1130]/80 via-transparent"/><div className="absolute inset-x-6 bottom-6 rounded-[22px] bg-white/10 p-5 backdrop-blur-md"><p className="text-xs leading-relaxed text-white/75">Symbolisches Bild. Fahrzeug, Hotel und genauer Leistungsumfang werden vor der Buchung schriftlich bestätigt.</p></div></div><div className="glass-dark rounded-[38px] p-7 md:p-10"><p className="eyebrow !text-[#a3c2ff]">Reiseorganisation</p><h2 className="mt-5 text-[clamp(2rem,7vw,5rem)] font-black leading-[.95] tracking-[-.04em] md:leading-[.9] md:tracking-[-.05em]">Flughafen, Unterkunft & Transfer.</h2><p className="mt-6 max-w-lg leading-relaxed text-white/70">Damit Sie sich auf Ihre Behandlung konzentrieren können, koordinieren wir die organisatorischen Schritte Ihrer Reise nach Antalya.</p><div className="mt-9 grid gap-3 sm:grid-cols-2">{steps.map(([n,t,d])=><div key={n} className="rounded-[24px] border border-white/10 bg-white/[.06] p-5 backdrop-blur-xl"><span className="text-[10px] font-black text-[#a3c2ff]">{n}</span><h3 className="mt-3 font-black">{t}</h3><p className="mt-2 text-xs leading-relaxed text-white/70">{d}</p></div>)}</div><div className="mt-8 flex flex-col gap-4 border-t border-white/10 pt-7 sm:flex-row sm:items-center sm:justify-between"><p className="max-w-sm text-[11px] leading-relaxed text-white/65">Flug, Unterkunft und Transfer sind nur enthalten, wenn dies im individuellen Angebot ausdrücklich angegeben ist.</p><Link to="/randevu-al" className="shrink-0 rounded-full bg-[#4da8ff] px-6 py-4 text-center text-sm font-bold text-[#0a1130]">Reise anfragen ↗</Link></div></div></div></div></section>
}
