import { useEffect } from 'react'
import { Link, Navigate, useParams } from 'react-router-dom'
import { blogData } from '../shared/blogData'
import { translate, useI18n } from '../shared/i18n'

export default function BlogDetail() {
  const { slug } = useParams(); const post = blogData.find(p => p.slug === slug)
  const { language } = useI18n()
  useEffect(() => { if (!post) return; document.title = `${translate(post.title, language)} | Smilevia`; let meta = document.querySelector('meta[name="description"]'); if (!meta) { meta=document.createElement('meta'); meta.setAttribute('name','description'); document.head.appendChild(meta) } meta.setAttribute('content',translate(post.description, language)); let keywords = document.querySelector('meta[name="keywords"]'); if (!keywords) { keywords=document.createElement('meta'); keywords.setAttribute('name','keywords'); document.head.appendChild(keywords) } keywords.setAttribute('content',post.keywords) }, [post, language])
  if (!post) return <Navigate to="/blog" replace />
  const schema = { '@context':'https://schema.org','@type':'Article', headline:post.title, description:post.description, image:post.image, author:{'@type':'Organization',name:'Smilevia'}, publisher:{'@type':'Organization',name:'Smilevia'}, datePublished:'2026-08-26', dateModified:'2026-08-26' }
  return <main id="main-content" className="min-h-screen bg-[#f3f5fb] px-4 pb-24 pt-28 text-[#0a1130] md:px-8 md:pt-36"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/><article className="mx-auto max-w-[1000px]"><Link to="/blog" className="text-sm font-black text-[#596988]">← Alle Ratgeber</Link><p className="eyebrow mt-10">{post.category}</p><h1 className="mt-5 text-[clamp(2rem,9vw,6.5rem)] font-black leading-[.95] tracking-[-.04em] md:leading-[.88] md:tracking-[-.055em]">{post.title}</h1><p className="mt-7 max-w-3xl text-lg leading-relaxed text-[#55607a]">{post.description}</p><div className="mt-10 overflow-hidden rounded-[38px]"><img src={post.image} alt={post.title} className="w-full object-cover"/><p className="border-t border-white/50 bg-white/50 px-5 py-3 text-[11px] backdrop-blur-xl text-[#626c85]">KI-generiertes, symbolisches Titelbild · keine Darstellung eines konkreten Behandlungsergebnisses</p></div><div className="mt-10 grid gap-5 lg:grid-cols-[1fr_280px]"><div className="glass rounded-[34px] p-7 md:p-12">{post.sections.map(([title,text])=><section key={title} className="border-b border-[#e5e9f7] py-8 first:pt-0 last:border-0"><h2 className="text-2xl font-black">{title}</h2><p className="mt-4 leading-7 text-[#55607a]">{text}</p></section>)}<div className="mt-8 rounded-[24px] border border-white/50 bg-white/40 p-5 text-xs backdrop-blur-xl leading-relaxed text-[#596378]"><b>Medizinischer Hinweis:</b> Dieser Beitrag dient der allgemeinen Orientierung und ersetzt keine Untersuchung, Diagnose oder persönliche Behandlungsempfehlung.</div></div><aside className="h-fit glass rounded-[30px] bg-[#4da8ff]/50 p-6 lg:sticky lg:top-32"><p className="eyebrow">Kostenlose Anfrage</p><h2 className="mt-4 text-2xl font-black">Ihre Situation persönlich besprechen</h2><p className="mt-3 text-sm text-[#4a5170]">Wir koordinieren eine erste Einschätzung durch unsere ausgewählte Partnerklinik.</p><Link to="/randevu-al" className="mt-6 block rounded-full bg-[#15265e] px-5 py-4 text-center text-sm font-bold text-white">Anfrage starten ↗</Link></aside></div></article></main>
}
