import { Link } from 'react-router-dom'
import { TravelSupport } from '../shared/TravelSupport'
import { Testimonials } from '../shared/Testimonials'
import { serviceData } from '../shared/serviceData'
import { SeoGuide } from '../shared/SeoGuide'
import { PremiumHero } from '../shared/PremiumHero'
import { PremiumProcess } from '../shared/PremiumProcess'
import { Faq } from '../shared/Faq'
import { GeoCoverage } from '../shared/GeoCoverage'

export default function Home() {
  return <main id="main-content" className="overflow-hidden bg-[#f3f5fb] text-[#0a1130]">
    <PremiumHero/>
    <section className="px-4 py-20 md:px-8 md:py-28"><div className="mx-auto max-w-[1320px]"><p className="eyebrow">Zahnmedizin in Antalya</p><div className="mt-5 flex flex-col justify-between gap-6 md:flex-row md:items-end"><h2 className="section-title">Behandlungen für Ihr<br/><span className="hero-script font-normal italic text-[#4f6fd6]">gesundes Lächeln.</span></h2><Link to="/hizmetlerimiz" className="font-black">Alle Behandlungen ↗</Link></div><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{serviceData.slice(0,6).map(service=><article key={service.slug} className="glass group overflow-hidden rounded-[30px] transition duration-500 hover:-translate-y-2 hover:bg-white/70 hover:shadow-[0_24px_60px_rgba(10,17,48,.14)]"><Link to={`/hizmetlerimiz/${service.slug}`}><img src={service.image} alt={service.title} className="h-64 w-full object-cover transition duration-700 group-hover:scale-105"/></Link><div className="p-7"><p className="eyebrow">{service.category}</p><h3 className="mt-4 text-2xl font-black">{service.title}</h3><p className="mt-3 text-sm leading-relaxed text-[#5b6478]">{service.summary}</p><Link to={`/hizmetlerimiz/${service.slug}`} className="mt-6 inline-block text-sm font-black">Details ↗</Link></div></article>)}</div></div></section>
    <section className="px-4 py-20 md:px-8 md:py-28"><div className="mx-auto grid max-w-[1320px] gap-5 lg:grid-cols-2"><div className="relative min-h-[560px] overflow-hidden rounded-[36px]"><img src="/smilevia-media/home-3.webp" alt="Moderne Partnerklinik in Antalya" className="h-full w-full object-cover"/></div><div className="glass rounded-[36px] p-7 md:p-12"><p className="eyebrow">Unsere Rolle</p><h2 className="section-title mt-5">Sie sprechen<br/>immer mit uns.</h2><p className="mt-7 max-w-md leading-relaxed text-[#596378]">Smilevia begleitet und koordiniert Ihre Anfrage. Die medizinische Beratung, Diagnose und Behandlung erfolgen ausschliesslich durch unsere ausgewählte Partnerklinik.</p><div className="mt-12 grid grid-cols-3 gap-3 border-t border-[#e4e9f5] pt-8">{[['DE','Beratung'],['1:1','Begleitung'],['TR','Behandlung']].map(item=><div key={item[1]}><b className="text-2xl md:text-3xl">{item[0]}</b><p className="mt-1 text-xs text-[#626c85]">{item[1]}</p></div>)}</div><Link to="/hakkimizda" className="mt-10 inline-block rounded-full bg-[#15265e] px-6 py-4 font-bold text-white">Über Smilevia ↗</Link></div></div></section>
    <section className="px-4 py-20 md:px-8 md:py-28"><div className="mx-auto max-w-[1320px]"><div className="grid gap-8 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><p className="eyebrow">Unser Netzwerk</p><h2 className="section-title mt-5">Unsere<br/><span className="hero-script font-normal italic text-[#4f6fd6]">Partnerschaften.</span></h2></div><p className="max-w-2xl leading-relaxed text-[#596378]">Für einen gut koordinierten Aufenthalt arbeiten wir mit ausgewählten medizinischen und organisatorischen Partnern in Antalya zusammen. Der konkrete medizinische Leistungserbringer und alle gebuchten Leistungen werden Ihnen vor einer verbindlichen Entscheidung transparent offengelegt.</p></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['01','Partnerklinik','Diagnostik, Behandlungsplanung und zahnmedizinische Versorgung.'],['02','Dentallabor','Individuell angefertigter Zahnersatz nach Behandlungsplanung.'],['03','Transfernetzwerk','Koordination der Fahrten zwischen Flughafen, Unterkunft und Klinik.'],['04','Unterkunftspartner','Unterstützung bei der Auswahl einer passenden Unterkunft.']].map(([n,title,text])=><article key={n} className="glass group rounded-[28px] p-7 transition duration-500 hover:-translate-y-2 hover:bg-white/70 hover:shadow-[0_20px_50px_rgba(10,17,48,.1)]"><div className="flex h-11 w-11 items-center justify-center rounded-full bg-[#15265e] text-xs font-black text-[#4da8ff]">{n}</div><h3 className="mt-12 text-xl font-black">{title}</h3><p className="mt-3 text-sm leading-relaxed text-[#5b6478]">{text}</p></article>)}</div><p className="mt-7 text-xs leading-relaxed text-[#6b7488]">Hinweis: Die Darstellung beschreibt unser Koordinationsnetzwerk und ist keine Garantie bestimmter Anbieter oder Leistungen. Verbindlich ist ausschliesslich Ihr individuelles schriftliches Angebot.</p></div></section>
    <PremiumProcess/><SeoGuide/><TravelSupport/><GeoCoverage/><Testimonials/><Faq/>
  </main>
}
